# Generated by Django 2.2.18 on 2021-02-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('1', '学生'), ('2', '教师')], default='学生', max_length=10, verbose_name='类别'),
        ),
    ]
