# Generated by Django 2.2.18 on 2021-02-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='category',
            field=models.CharField(choices=[('1', '学生'), ('2', '教师'), ('0', '系统管理人员')], max_length=10, verbose_name='类别'),
        ),
    ]
